spring.application.name=ridelink

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ridelink
spring.datasource.username=root
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server Configuration
# ===============================
server.port=8080
server.servlet.context-path=/api

# ===============================
# Jwt Configuration
# ===============================

jwt_secret=dfdfadsfadfesnvn4nreDFCSsEdsdvSddn245n5n4nnndfjeurusenen424n2n42n4nsd42n4n52055inrnidfdifnnvsdfADdc
jwt_expiration=86400000